# Generated by Django 3.2.5 on 2021-07-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='april',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='august',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='december',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='february',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='january',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='july',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='june',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='march',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='may',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='november',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='october',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='september',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='total_annual',
            field=models.IntegerField(),
        ),
    ]
